services:
  database:
    image: postgres:13.1
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
    volumes:
    - database-data:/var/lib/postgresql/data

volumes:
  database-data:
